required = [
  "k8s.io/code-generator/cmd/deepcopy-gen",
]

[prune]
  go-tests = true
  unused-packages = true

  [[prune.project]]
    name = "sigs.k8s.io/cluster-api"
    unused-packages = false

[[constraint]]
  revision = "7db708b5df567c79e2e46f9c37cdbf001bef1302"
  name = "sigs.k8s.io/cluster-api"

[[constraint]]
  name = "github.com/joho/godotenv"
  version = "1.2.0"

[[constraint]]
  name = "github.com/Azure/azure-sdk-for-go"
  version = "17.2.0"

[[constraint]]
  name = "github.com/Azure/go-autorest"
  version = "10.10.0"

[[constraint]]
  name = "github.com/ghodss/yaml"
  version = "1.0.0"

[[constraint]]
  name = "k8s.io/code-generator"
  branch = "release-1.9"