[[constraint]]
  name = "github.com/joho/godotenv"
  version = "1.2.0"

[[constraint]]
  name = "github.com/Azure/azure-sdk-for-go"
  version = "17.2.0"

[[constraint]]
  name = "github.com/Azure/go-autorest"
  version = "10.10.0"

[[constraint]]
  name = "github.com/ghodss/yaml"
  version = "1.0.0"

[[constraint]]
  branch = "release-1.9"
  name = "k8s.io/apimachinery"

[prune]
  go-tests = true
  unused-packages = true

[[constraint]]
  branch = "master"
  name = "sigs.k8s.io/cluster-api"
