apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  creationTimestamp: null
  labels:
    controller-tools.k8s.io: "1.0"
  name: azureclusterproviderstatuses.azureprovider.k8s.io
spec:
  group: azureprovider.k8s.io
  names:
    kind: AzureClusterProviderStatus
    plural: azureclusterproviderstatuses
  scope: Namespaced
  validation:
    openAPIV3Schema:
      properties:
        apiVersion:
          type: string
        bastion:
          properties:
            ebsOptimized:
              type: boolean
            enaSupport:
              type: boolean
            iamProfile:
              type: string
            id:
              type: string
            imageId:
              type: string
            instanceState:
              type: string
            keyName:
              type: string
            privateIp:
              type: string
            publicIp:
              type: string
            securityGroupIds:
              items:
                type: string
              type: array
            subnetId:
              type: string
            tags:
              type: object
            type:
              type: string
            userData:
              type: string
          required:
          - id
          type: object
        kind:
          type: string
        metadata:
          type: object
        network:
          properties:
            apiServerIp:
              properties:
                id:
                  type: string
                ipAddress:
                  type: string
              required:
              - id
              - ipAddress
              type: object
            apiServerLb:
              properties:
                dnsName:
                  type: string
                healthChecks:
                  properties:
                    healthyThreshold:
                      format: int64
                      type: integer
                    interval:
                      format: int64
                      type: integer
                    target:
                      type: string
                    timeout:
                      format: int64
                      type: integer
                    unhealthyThreshold:
                      format: int64
                      type: integer
                  required:
                  - target
                  - interval
                  - timeout
                  - healthyThreshold
                  - unhealthyThreshold
                  type: object
                ipAddress:
                  type: string
                listeners:
                  items:
                    properties:
                      instancePort:
                        format: int64
                        type: integer
                      instanceProtocol:
                        type: string
                      port:
                        format: int64
                        type: integer
                      protocol:
                        type: string
                    required:
                    - protocol
                    - port
                    - instanceProtocol
                    - instancePort
                    type: object
                  type: array
                name:
                  type: string
                scheme:
                  type: string
                securityGroupIds:
                  items:
                    type: string
                  type: array
                subnetIds:
                  items:
                    type: string
                  type: array
                tags:
                  type: object
              type: object
            internetGatewayId:
              type: string
            securityGroups:
              type: object
            subnets:
              items:
                properties:
                  cidrBlock:
                    type: string
                  id:
                    type: string
                  nsgId:
                    type: string
                  routeTableId:
                    type: string
                  vnetId:
                    type: string
                required:
                - id
                - vnetId
                - cidrBlock
                - nsgId
                - routeTableId
                type: object
              type: array
            vnet:
              properties:
                cidrBlock:
                  type: string
                id:
                  type: string
                name:
                  type: string
                tags:
                  type: object
              required:
              - id
              - cidrBlock
              - tags
              type: object
          type: object
  version: v1alpha1
status:
  acceptedNames:
    kind: ""
    plural: ""
  conditions: []
  storedVersions: []
