apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  creationTimestamp: null
  labels:
    controller-tools.k8s.io: "1.0"
  name: azureclusterproviderstatuses.azureprovider.k8s.io
spec:
  group: azureprovider.k8s.io
  names:
    kind: AzureClusterProviderStatus
    plural: azureclusterproviderstatuses
  scope: Namespaced
  validation:
    openAPIV3Schema:
      properties:
        apiVersion:
          description: 'APIVersion defines the versioned schema of this representation
            of an object. Servers should convert recognized schemas to the latest
            internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/api-conventions.md#resources'
          type: string
        bastion:
          properties:
            id:
              type: string
            identity:
              type: string
            image:
              description: Storage profile
              properties:
                offer:
                  type: string
                publisher:
                  type: string
                sku:
                  type: string
                version:
                  type: string
              required:
              - publisher
              - offer
              - sku
              - version
              type: object
            name:
              type: string
            osDisk:
              properties:
                diskSizeGB:
                  format: int32
                  type: integer
                managedDisk:
                  properties:
                    storageAccountType:
                      type: string
                  required:
                  - storageAccountType
                  type: object
                osType:
                  type: string
              required:
              - osType
              - managedDisk
              - diskSizeGB
              type: object
            startupScript:
              type: string
            tags:
              type: object
            vmSize:
              description: Hardware profile
              type: string
            vmState:
              description: State - The provisioning state, which only appears in the
                response.
              type: string
          type: object
        kind:
          description: 'Kind is a string value representing the REST resource this
            object represents. Servers may infer this from the endpoint the client
            submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/api-conventions.md#types-kinds'
          type: string
        metadata:
          type: object
        network:
          properties:
            apiServerIp:
              description: 'APIServerIP is the Kubernetes API server public IP address.
                TODO: Remove once load balancer is implemented.'
              properties:
                id:
                  type: string
                ipAddress:
                  type: string
                name:
                  type: string
              required:
              - id
              - name
              - ipAddress
              type: object
            apiServerLb:
              description: APIServerLB is the Kubernetes API server load balancer.
              properties:
                frontendIpConfig:
                  type: object
                id:
                  type: string
                name:
                  type: string
                sku:
                  type: string
                tags:
                  type: object
              type: object
            securityGroups:
              description: SecurityGroups is a map from the role/kind of the security
                group to its unique name, if any.
              type: object
            subnets:
              description: Subnets includes all the subnets defined inside the Vnet.
              items:
                properties:
                  cidrBlock:
                    type: string
                  id:
                    type: string
                  name:
                    type: string
                  securityGroup:
                    properties:
                      id:
                        type: string
                      ingressRule:
                        items:
                          properties:
                            description:
                              type: string
                            destination:
                              description: Destination - The destination address prefix.
                                CIDR or destination IP range. Asterix '*' can also
                                be used to match all source IPs. Default tags such
                                as 'VirtualNetwork', 'AzureLoadBalancer' and 'Internet'
                                can also be used.
                              type: string
                            destinationPorts:
                              description: DestinationPorts - The destination port
                                or range. Integer or range between 0 and 65535. Asterix
                                '*' can also be used to match all ports.
                              type: string
                            protocol:
                              type: string
                            source:
                              description: Source - The CIDR or source IP range. Asterix
                                '*' can also be used to match all source IPs. Default
                                tags such as 'VirtualNetwork', 'AzureLoadBalancer'
                                and 'Internet' can also be used. If this is an ingress
                                rule, specifies where network traffic originates from.
                              type: string
                            sourcePorts:
                              description: SourcePorts - The source port or range.
                                Integer or range between 0 and 65535. Asterix '*'
                                can also be used to match all ports.
                              type: string
                          required:
                          - description
                          - protocol
                          type: object
                        type: array
                      name:
                        type: string
                      tags:
                        type: object
                    required:
                    - id
                    - name
                    - ingressRule
                    - tags
                    type: object
                  vnetId:
                    type: string
                required:
                - name
                - vnetId
                - cidrBlock
                - securityGroup
                type: object
              type: array
            vnet:
              description: Vnet defines the cluster vnet.
              properties:
                cidrBlock:
                  type: string
                id:
                  type: string
                name:
                  type: string
                tags:
                  type: object
              required:
              - cidrBlock
              - tags
              type: object
          type: object
  version: v1alpha1
status:
  acceptedNames:
    kind: ""
    plural: ""
  conditions: []
  storedVersions: []
