[book]
authors = ["The Cluster API Provider Azure Maintainers"]
language = "en"
multilingual = false
src = "src"
title = "The Cluster API Provider Azure Book"

[build]
build-dir = "bookout"
create-missing = false

[output.html]
curly-quotes = true
git-repository-url = "https://sigs.k8s.io/cluster-api-provider-azure"

[preprocessor.tabulate]
command = "./util-tabulate.sh"

[preprocessor.embed]
command = "./util-embed.sh"

[preprocessor.releaselink]
command = "./util-releaselink.sh"
