---
apiVersion: cluster.x-k8s.io/v1alpha4
kind: MachineDeployment
metadata:
  name: "${CLUSTER_NAME}-md-0"
spec:
  clusterName: "${CLUSTER_NAME}"
  replicas: ${LINUX_WORKER_MACHINE_COUNT:-1}
  selector:
    matchLabels:
  template:
    spec:
      clusterName: "${CLUSTER_NAME}"
      version: "${KUBERNETES_VERSION}"
      bootstrap:
        configRef:
          name: "${CLUSTER_NAME}-md-0"
          apiVersion: bootstrap.cluster.x-k8s.io/v1alpha4
          kind: KubeadmConfigTemplate
      infrastructureRef:
        name: "${CLUSTER_NAME}-md-0"
        apiVersion: infrastructure.cluster.x-k8s.io/v1alpha4
        kind: AzureMachineTemplate
---
apiVersion: infrastructure.cluster.x-k8s.io/v1alpha4
kind: AzureMachineTemplate
metadata:
  name: "${CLUSTER_NAME}-md-0"
spec:
  template:
    spec:
      vmSize: ${AZURE_NODE_MACHINE_TYPE}
      osDisk:
        osType: "Linux"
        diskSizeGB: 128
        managedDisk:
          storageAccountType: "Premium_LRS"
      sshPublicKey: ${AZURE_SSH_PUBLIC_KEY_B64:=""}
---
apiVersion: bootstrap.cluster.x-k8s.io/v1alpha4
kind: KubeadmConfigTemplate
metadata:
  name: "${CLUSTER_NAME}-md-0"
spec:
  template:
    spec:
      preKubeadmCommands: []
      postKubeadmCommands:
        # Azures vnet MTU is 1400. 
        # When using Flannel VXLAN to avoid packet fragmentation 
        # that results dropped packets on Windows we need to match.
        # Flannel will automatically choose eth0 - 50
        - mac=$(ip -o link | grep eth0 | grep ether | awk '{ print $17 }')
        - sed -i -e "s/MACADDRESS/$${mac}/g" /etc/netplan/60-eth0.yaml
        - netplan apply 
      useExperimentalRetryJoin: true
      joinConfiguration:
        nodeRegistration:
          name: '{{ ds.meta_data["local_hostname"] }}'
          kubeletExtraArgs:
            cloud-provider: azure
            cloud-config: /etc/kubernetes/azure.json
            azure-container-registry-config: /etc/kubernetes/azure.json
      files:
      - contentFrom:
          secret:
            name: ${CLUSTER_NAME}-md-0-azure-json
            key: worker-node-azure.json
        owner: root:root
        path: /etc/kubernetes/azure.json
        permissions: "0644"
      - path: /etc/netplan/60-eth0.yaml
        permissions: "0644"
        owner: root:root
        content: |
          network:
            version: 2
            ethernets:
              eth0:
                mtu: 1400
                match:
                  macaddress: MACADDRESS
                set-name: eth0
      