apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: azureasomanagedcontrolplanetemplates.infrastructure.cluster.x-k8s.io
  labels:
    cluster.x-k8s.io/v1beta1: v1alpha1
