namePrefix: capz-

# Labels to add to all resources and selectors.
commonLabels:
  cluster.x-k8s.io/provider: "infrastructure-azure"
bases:
  - crd
  - webhook
  - default

patchesJson6902:
  - target:
      group: apiextensions.k8s.io
      version: v1
      kind: CustomResourceDefinition
      name: azureclusters.infrastructure.cluster.x-k8s.io
    path: patch_crd_webhook_namespace.yaml
  - target:
      group: apiextensions.k8s.io
      version: v1
      kind: CustomResourceDefinition
      name: azuremachines.infrastructure.cluster.x-k8s.io
    path: patch_crd_webhook_namespace.yaml
  - target:
      group: apiextensions.k8s.io
      version: v1
      kind: CustomResourceDefinition
      name: azuremachinetemplates.infrastructure.cluster.x-k8s.io
    path: patch_crd_webhook_namespace.yaml
