apiVersion: v2
appVersion: v1.1.1
description: A Helm Chart for installing the Cluster API Visualizer
maintainers:
- email: jt572@cornell.edu
  name: Jonathan Tong
name: cluster-api-visualizer
sources:
- https://github.com/Jont828/cluster-api-visualizer
type: application
version: 1.1.1
