apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: default
resources:
- ../base
- ../../azure-cluster-identity
- machine-deployment.yaml


generatorOptions:
  annotations:
    note: generated
  disableNameSuffixHash: true
  labels:
    type: generated

patches:
- path: ../../azure-cluster-identity/azurecluster-identity-ref.yaml
- path: ../../internal-load-balancer/azure-cluster-frontend-ip.yaml
- path: ../../internal-load-balancer/kubeadm-config-template-worker-node.yaml

sortOptions:
  order: fifo
