apiVersion: bootstrap.cluster.x-k8s.io/v1beta1
kind: KubeadmConfigTemplate
metadata:
  name: "${CLUSTER_NAME}-md-0"
spec:
  template:
    spec:
      # /etc/hosts file is updated with a pre-created DNS name of the API server and internal load-balancer's IP.
      # This custom DNS Resolution of the API server ensures that the worker nodes can reach the API server when
      # the public IP of the API server is not accessible.
      # 10.0.0.100 is the IP that gets assigned to an internal load balancer.
      preKubeadmCommands:
        - echo '10.0.0.100   ${CLUSTER_NAME}-${APISERVER_LB_DNS_SUFFIX}.${AZURE_LOCATION}.cloudapp.azure.com' >> /etc/hosts
