{{- if .Values.enabled }}
{{- if .Values.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "jaeger-all-in-one.serviceAccountName" . }}
  namespace: {{ .Release.Namespace }}
  labels:
{{ include "jaeger-all-in-one.labels" . | nindent 4 }}
{{- end -}}
{{- end }}
