apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: capi-visualizer
rules:
- apiGroups:
  - ''
  resources:
  - '*'
  verbs:
  - 'list'
  - 'get'
  - 'watch'
- apiGroups:
  - 'apiextensions.k8s.io'
  resources:
  - 'customresourcedefinitions'
  verbs:
  - 'list'
  - 'get'
  - 'watch'
- apiGroups:
  - 'cluster.x-k8s.io'
  - 'addons.cluster.x-k8s.io'
  - 'bootstrap.cluster.x-k8s.io'
  - 'controlplane.cluster.x-k8s.io'
  - 'ipam.cluster.x-k8s.io'
  - 'infrastructure.cluster.x-k8s.io'
  - 'runtime.cluster.x-k8s.io'
  resources:
  - '*'
  verbs:
  - '*'
# Note: this is a fallback to allow the visualizer to work with user-specific CRDs.
- apiGroups:
  - '*'
  resources:
  - '*'
  verbs:
  - 'list'
  - 'get'
  - 'watch'
- nonResourceURLs:
  - '*'
  verbs:
  - '*'
