apiVersion: v1
kind: Service
metadata:
  name: capi-visualizer
  namespace: {{ .Release.Namespace }}
  labels:
    {{ .Values.label.key }}: {{ .Values.label.value }}
spec:
  ports:
  - port: 8081
    targetPort: 8081
    protocol: TCP
  selector:
    {{ .Values.label.key }}: {{ .Values.label.value }}
