---
apiVersion: cluster.x-k8s.io/v1beta1
kind: MachinePool
metadata:
  name: "${CLUSTER_NAME}-mp-win"
spec:
  clusterName: "${CLUSTER_NAME}"
  replicas: ${WORKER_MACHINE_COUNT:=2}
  template:
    spec:
      clusterName: "${CLUSTER_NAME}"
      version: "${KUBERNETES_VERSION}"
      bootstrap:
        configRef:
          name: "${CLUSTER_NAME}-mp-win"
          apiVersion: bootstrap.cluster.x-k8s.io/v1beta1
          kind: KubeadmConfig
      infrastructureRef:
        name: "${CLUSTER_NAME}-mp-win"
        apiVersion: infrastructure.cluster.x-k8s.io/v1beta1
        kind: AzureMachinePool
---
apiVersion: infrastructure.cluster.x-k8s.io/v1beta1
kind: AzureMachinePool
metadata:
  name: "${CLUSTER_NAME}-mp-win"
  annotations:
    runtime: containerd
    windowsServerVersion: ${WINDOWS_SERVER_VERSION:=""}
spec:
  location: ${AZURE_LOCATION}
  template:
    vmSize: ${AZURE_NODE_MACHINE_TYPE}
    osDisk:
      osType: "Windows"
      diskSizeGB: 128
      managedDisk:
        storageAccountType: "Premium_LRS"
    sshPublicKey: ${AZURE_SSH_PUBLIC_KEY_B64:=""}
---
apiVersion: bootstrap.cluster.x-k8s.io/v1beta1
kind: KubeadmConfig
metadata:
  name: "${CLUSTER_NAME}-mp-win"
spec:
  users:
  - name: capi
    groups: Administrators
    sshAuthorizedKeys:
    - ${AZURE_SSH_PUBLIC_KEY:=""}
  preKubeadmCommands:
    - powershell c:/create-external-network.ps1
  postKubeadmCommands:
    - powershell C:/KubeletRestart_nssm_sc.ps1
    - powershell C:/defender-exclude-calico.ps1
  joinConfiguration:
    nodeRegistration:
      name: '{{ ds.meta_data["local_hostname"] }}'
      criSocket: npipe:////./pipe/containerd-containerd
      kubeletExtraArgs:
        cloud-provider: external
  files:
  - contentFrom:
      secret:
        name: ${CLUSTER_NAME}-mp-win-azure-json
        key: worker-node-azure.json
    owner: root:root
    path: c:/k/azure.json
    permissions: "0644"
  - content: |
      # This script restarts the kubelet service.
      # It supports both nssm and Windows service configurations,
      # ensuring a smooth transition between service managers without interruption.
      # This script will eventually be removed once nssm is no longer used.
      $scriptPath = "$env:SYSTEMDRIVE/k/RestartKubelet.ps1"
      if (Test-Path $scriptPath) {
          Write-Host "Found RestartKubelet.ps1, executing..."
          & $scriptPath
      } else {
          Write-Host "RestartKubelet.ps1 not found. Running fallback command..."
          & "$env:SYSTEMDRIVE\k\nssm.exe" set kubelet start SERVICE_AUTO_START
      }
    path: C:/KubeletRestart_nssm_sc.ps1
    permissions: "0744"
  - path: C:/defender-exclude-calico.ps1
    permissions: "0744"
    content: |-
      Add-MpPreference -ExclusionProcess C:/opt/cni/bin/calico.exe
