apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: default
resources:
- clusterclass.yaml
- azure-managed-controlplane-template.yaml
- azure-managed-cluster-template.yaml
- azure-managed-machinepool-template.yaml
- kubeadm-config-template.yaml
