apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: default
resources:
- ../base
- machine-pool-deployment.yaml
- ../../azure-cluster-identity

patches:
- path: ../../azure-cluster-identity/azurecluster-identity-ref.yaml

sortOptions:
  order: fifo
