apiVersion: controlplane.cluster.x-k8s.io/v1alpha3
kind: KubeadmControlPlane
metadata:
  name: "${CLUSTER_NAME}-control-plane"
spec:
  kubeadmConfigSpec:
    useExperimentalRetryJoin: true
    initConfiguration:
      nodeRegistration:
        name: '{{ ds.meta_data["local_hostname"] }}'
        kubeletExtraArgs:
          cloud-provider: azure
          cloud-config: /etc/kubernetes/azure.json
          node-ip: "::"
          cluster-dns: "fd00::10"
      localAPIEndpoint:
        advertiseAddress: "::"
        bindPort: 6443
    joinConfiguration:
      nodeRegistration:
        name: '{{ ds.meta_data["local_hostname"] }}'
        kubeletExtraArgs:
          cloud-provider: azure
          cloud-config: /etc/kubernetes/azure.json
          node-ip: "::"
          cluster-dns: "fd00::10"
      controlPlane:
        localAPIEndpoint:
          advertiseAddress: "::"
          bindPort: 6443
    clusterConfiguration:
      apiServer:
        timeoutForControlPlane: 20m
        extraArgs:
          cloud-provider: azure
          cloud-config: /etc/kubernetes/azure.json
          bind-address: "::"
      controllerManager:
        extraArgs:
          cloud-provider: azure
          cloud-config: /etc/kubernetes/azure.json
          #required for ipv6 using calico
          allocate-node-cidrs: "true"
          cluster-cidr: "2001:1234:5678:9a40::/58"
          configure-cloud-routes: "true"
          bind-address: "::"
      scheduler:
        extraArgs:
          bind-address: "::"
    