
---
apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  annotations:
    controller-gen.kubebuilder.io/version: v0.6.1
  creationTimestamp: null
  name: azuremanagedcontrolplanes.infrastructure.cluster.x-k8s.io
spec:
  group: infrastructure.cluster.x-k8s.io
  names:
    categories:
    - cluster-api
    kind: AzureManagedControlPlane
    listKind: AzureManagedControlPlaneList
    plural: azuremanagedcontrolplanes
    shortNames:
    - amcp
    singular: azuremanagedcontrolplane
  scope: Namespaced
  versions:
  - name: v1alpha3
    schema:
      openAPIV3Schema:
        description: AzureManagedControlPlane is the Schema for the azuremanagedcontrolplanes
          API.
        properties:
          apiVersion:
            description: 'APIVersion defines the versioned schema of this representation
              of an object. Servers should convert recognized schemas to the latest
              internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#resources'
            type: string
          kind:
            description: 'Kind is a string value representing the REST resource this
              object represents. Servers may infer this from the endpoint the client
              submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds'
            type: string
          metadata:
            type: object
          spec:
            description: AzureManagedControlPlaneSpec defines the desired state of
              AzureManagedControlPlane.
            properties:
              additionalTags:
                additionalProperties:
                  type: string
                description: AdditionalTags is an optional set of tags to add to Azure
                  resources managed by the Azure provider, in addition to the ones
                  added by default.
                type: object
              controlPlaneEndpoint:
                description: ControlPlaneEndpoint represents the endpoint used to
                  communicate with the control plane.
                properties:
                  host:
                    description: The hostname on which the API server is serving.
                    type: string
                  port:
                    description: The port on which the API server is serving.
                    format: int32
                    type: integer
                required:
                - host
                - port
                type: object
              defaultPoolRef:
                description: DefaultPoolRef is the specification for the default pool,
                  without which an AKS cluster cannot be created.
                properties:
                  name:
                    description: 'Name of the referent. More info: https://kubernetes.io/docs/concepts/overview/working-with-objects/names/#names
                      TODO: Add other useful fields. apiVersion, kind, uid?'
                    type: string
                type: object
              dnsServiceIP:
                description: DNSServiceIP is an IP address assigned to the Kubernetes
                  DNS service. It must be within the Kubernetes service address range
                  specified in serviceCidr.
                type: string
              loadBalancerSKU:
                description: LoadBalancerSKU is the SKU of the loadBalancer to be
                  provisioned.
                enum:
                - Basic
                - Standard
                type: string
              location:
                description: 'Location is a string matching one of the canonical Azure
                  region names. Examples: "westus2", "eastus".'
                type: string
              networkPlugin:
                description: NetworkPlugin used for building Kubernetes network.
                enum:
                - azure
                - kubenet
                type: string
              networkPolicy:
                description: NetworkPolicy used for building Kubernetes network.
                enum:
                - azure
                - calico
                type: string
              nodeResourceGroupName:
                description: NodeResourceGroupName is the name of the resource group
                  containining cluster IaaS resources. Will be populated to default
                  in webhook.
                type: string
              resourceGroupName:
                description: ResourceGroupName is the name of the Azure resource group
                  for this AKS Cluster.
                type: string
              sshPublicKey:
                description: SSHPublicKey is a string literal containing an ssh public
                  key base64 encoded.
                type: string
              subscriptionID:
                description: SubscriotionID is the GUID of the Azure subscription
                  to hold this cluster.
                type: string
              version:
                description: Version defines the desired Kubernetes version.
                minLength: 2
                type: string
              virtualNetwork:
                description: VirtualNetwork describes the vnet for the AKS cluster.
                  Will be created if it does not exist.
                properties:
                  cidrBlock:
                    type: string
                  name:
                    type: string
                  subnet:
                    description: ManagedControlPlaneSubnet describes a subnet for
                      an AKS cluster.
                    properties:
                      cidrBlock:
                        type: string
                      name:
                        type: string
                    required:
                    - cidrBlock
                    - name
                    type: object
                required:
                - cidrBlock
                - name
                type: object
            required:
            - defaultPoolRef
            - location
            - nodeResourceGroupName
            - resourceGroupName
            - sshPublicKey
            - version
            type: object
          status:
            description: AzureManagedControlPlaneStatus defines the observed state
              of AzureManagedControlPlane.
            properties:
              initialized:
                description: Initialized is true when the the control plane is available
                  for initial contact. This may occur before the control plane is
                  fully ready. In the AzureManagedControlPlane implementation, these
                  are identical.
                type: boolean
              ready:
                description: Ready is true when the provider resource is ready.
                type: boolean
            type: object
        type: object
    served: true
    storage: false
    subresources:
      status: {}
  - name: v1alpha4
    schema:
      openAPIV3Schema:
        description: AzureManagedControlPlane is the Schema for the azuremanagedcontrolplanes
          API.
        properties:
          apiVersion:
            description: 'APIVersion defines the versioned schema of this representation
              of an object. Servers should convert recognized schemas to the latest
              internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#resources'
            type: string
          kind:
            description: 'Kind is a string value representing the REST resource this
              object represents. Servers may infer this from the endpoint the client
              submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds'
            type: string
          metadata:
            type: object
          spec:
            description: AzureManagedControlPlaneSpec defines the desired state of
              AzureManagedControlPlane.
            properties:
              additionalTags:
                additionalProperties:
                  type: string
                description: AdditionalTags is an optional set of tags to add to Azure
                  resources managed by the Azure provider, in addition to the ones
                  added by default.
                type: object
              controlPlaneEndpoint:
                description: ControlPlaneEndpoint represents the endpoint used to
                  communicate with the control plane.
                properties:
                  host:
                    description: The hostname on which the API server is serving.
                    type: string
                  port:
                    description: The port on which the API server is serving.
                    format: int32
                    type: integer
                required:
                - host
                - port
                type: object
              defaultPoolRef:
                description: DefaultPoolRef is the specification for the default pool,
                  without which an AKS cluster cannot be created.
                properties:
                  name:
                    description: 'Name of the referent. More info: https://kubernetes.io/docs/concepts/overview/working-with-objects/names/#names
                      TODO: Add other useful fields. apiVersion, kind, uid?'
                    type: string
                type: object
              dnsServiceIP:
                description: DNSServiceIP is an IP address assigned to the Kubernetes
                  DNS service. It must be within the Kubernetes service address range
                  specified in serviceCidr.
                type: string
              identityRef:
                description: IdentityRef is a reference to a AzureClusterIdentity
                  to be used when reconciling this cluster
                properties:
                  apiVersion:
                    description: API version of the referent.
                    type: string
                  fieldPath:
                    description: 'If referring to a piece of an object instead of
                      an entire object, this string should contain a valid JSON/Go
                      field access statement, such as desiredState.manifest.containers[2].
                      For example, if the object reference is to a container within
                      a pod, this would take on a value like: "spec.containers{name}"
                      (where "name" refers to the name of the container that triggered
                      the event) or if no container name is specified "spec.containers[2]"
                      (container with index 2 in this pod). This syntax is chosen
                      only to have some well-defined way of referencing a part of
                      an object. TODO: this design is not final and this field is
                      subject to change in the future.'
                    type: string
                  kind:
                    description: 'Kind of the referent. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds'
                    type: string
                  name:
                    description: 'Name of the referent. More info: https://kubernetes.io/docs/concepts/overview/working-with-objects/names/#names'
                    type: string
                  namespace:
                    description: 'Namespace of the referent. More info: https://kubernetes.io/docs/concepts/overview/working-with-objects/namespaces/'
                    type: string
                  resourceVersion:
                    description: 'Specific resourceVersion to which this reference
                      is made, if any. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#concurrency-control-and-consistency'
                    type: string
                  uid:
                    description: 'UID of the referent. More info: https://kubernetes.io/docs/concepts/overview/working-with-objects/names/#uids'
                    type: string
                type: object
              loadBalancerSKU:
                description: LoadBalancerSKU is the SKU of the loadBalancer to be
                  provisioned.
                enum:
                - Basic
                - Standard
                type: string
              location:
                description: 'Location is a string matching one of the canonical Azure
                  region names. Examples: "westus2", "eastus".'
                type: string
              networkPlugin:
                description: NetworkPlugin used for building Kubernetes network.
                enum:
                - azure
                - kubenet
                type: string
              networkPolicy:
                description: NetworkPolicy used for building Kubernetes network.
                enum:
                - azure
                - calico
                type: string
              nodeResourceGroupName:
                description: NodeResourceGroupName is the name of the resource group
                  containining cluster IaaS resources. Will be populated to default
                  in webhook.
                type: string
              resourceGroupName:
                description: ResourceGroupName is the name of the Azure resource group
                  for this AKS Cluster.
                type: string
              sshPublicKey:
                description: SSHPublicKey is a string literal containing an ssh public
                  key base64 encoded.
                type: string
              subscriptionID:
                description: SubscriptionID is the GUID of the Azure subscription
                  to hold this cluster.
                type: string
              version:
                description: Version defines the desired Kubernetes version.
                minLength: 2
                type: string
              virtualNetwork:
                description: VirtualNetwork describes the vnet for the AKS cluster.
                  Will be created if it does not exist.
                properties:
                  cidrBlock:
                    type: string
                  name:
                    type: string
                  subnet:
                    description: ManagedControlPlaneSubnet describes a subnet for
                      an AKS cluster.
                    properties:
                      cidrBlock:
                        type: string
                      name:
                        type: string
                    required:
                    - cidrBlock
                    - name
                    type: object
                required:
                - cidrBlock
                - name
                type: object
            required:
            - defaultPoolRef
            - location
            - resourceGroupName
            - sshPublicKey
            - version
            type: object
          status:
            description: AzureManagedControlPlaneStatus defines the observed state
              of AzureManagedControlPlane.
            properties:
              initialized:
                description: Initialized is true when the the control plane is available
                  for initial contact. This may occur before the control plane is
                  fully ready. In the AzureManagedControlPlane implementation, these
                  are identical.
                type: boolean
              ready:
                description: Ready is true when the provider resource is ready.
                type: boolean
            type: object
        type: object
    served: true
    storage: true
    subresources:
      status: {}
status:
  acceptedNames:
    kind: ""
    plural: ""
  conditions: []
  storedVersions: []
