
---
apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  annotations:
    controller-gen.kubebuilder.io/version: v0.2.9
  creationTimestamp: null
  name: azuremachinetemplates.infrastructure.cluster.x-k8s.io
spec:
  group: infrastructure.cluster.x-k8s.io
  names:
    categories:
    - cluster-api
    kind: AzureMachineTemplate
    listKind: AzureMachineTemplateList
    plural: azuremachinetemplates
    singular: azuremachinetemplate
  scope: Namespaced
  versions:
  - name: v1alpha2
    schema:
      openAPIV3Schema:
        description: AzureMachineTemplate is the Schema for the azuremachinetemplates
          API
        properties:
          apiVersion:
            description: 'APIVersion defines the versioned schema of this representation
              of an object. Servers should convert recognized schemas to the latest
              internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#resources'
            type: string
          kind:
            description: 'Kind is a string value representing the REST resource this
              object represents. Servers may infer this from the endpoint the client
              submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds'
            type: string
          metadata:
            type: object
          spec:
            description: AzureMachineTemplateSpec defines the desired state of AzureMachineTemplate
            properties:
              template:
                description: AzureMachineTemplateResource describes the data needed
                  to create am AzureMachine from a template
                properties:
                  spec:
                    description: Spec is the specification of the desired behavior
                      of the machine.
                    properties:
                      additionalTags:
                        additionalProperties:
                          type: string
                        description: AdditionalTags is an optional set of tags to
                          add to an instance, in addition to the ones added by default
                          by the Azure provider. If both the AzureCluster and the
                          AzureMachine specify the same tag name with different values,
                          the AzureMachine's value takes precedence.
                        type: object
                      allocatePublicIP:
                        description: AllocatePublicIP allows the ability to create
                          dynamic public ips for machines where this value is true.
                        type: boolean
                      availabilityZone:
                        properties:
                          enabled:
                            type: boolean
                          id:
                            type: string
                        type: object
                      image:
                        description: 'Image defines information about the image to
                          use for VM creation. There are three ways to specify an
                          image: by ID, by publisher, or by Shared Image Gallery.
                          If specifying an image by ID, only the ID field needs to
                          be set. If specifying an image by publisher, the Publisher,
                          Offer, SKU, and Version fields must be set. If specifying
                          an image from a Shared Image Gallery, the SubscriptionID,
                          ResourceGroup, Gallery, Name, and Version fields must be
                          set.'
                        properties:
                          gallery:
                            type: string
                          id:
                            type: string
                          name:
                            type: string
                          offer:
                            type: string
                          publisher:
                            type: string
                          resourceGroup:
                            type: string
                          sku:
                            type: string
                          subscriptionID:
                            type: string
                          version:
                            type: string
                        type: object
                      location:
                        type: string
                      osDisk:
                        properties:
                          diskSizeGB:
                            format: int32
                            type: integer
                          managedDisk:
                            properties:
                              storageAccountType:
                                type: string
                            required:
                            - storageAccountType
                            type: object
                          osType:
                            type: string
                        required:
                        - diskSizeGB
                        - managedDisk
                        - osType
                        type: object
                      providerID:
                        description: ProviderID is the unique identifier as specified
                          by the cloud provider.
                        type: string
                      sshPublicKey:
                        type: string
                      vmSize:
                        type: string
                    required:
                    - location
                    - osDisk
                    - sshPublicKey
                    - vmSize
                    type: object
                required:
                - spec
                type: object
            required:
            - template
            type: object
        type: object
    served: true
    storage: false
  - name: v1alpha3
    schema:
      openAPIV3Schema:
        description: AzureMachineTemplate is the Schema for the azuremachinetemplates
          API
        properties:
          apiVersion:
            description: 'APIVersion defines the versioned schema of this representation
              of an object. Servers should convert recognized schemas to the latest
              internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#resources'
            type: string
          kind:
            description: 'Kind is a string value representing the REST resource this
              object represents. Servers may infer this from the endpoint the client
              submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds'
            type: string
          metadata:
            type: object
          spec:
            description: AzureMachineTemplateSpec defines the desired state of AzureMachineTemplate
            properties:
              template:
                description: AzureMachineTemplateResource describes the data needed
                  to create an AzureMachine from a template
                properties:
                  spec:
                    description: Spec is the specification of the desired behavior
                      of the machine.
                    properties:
                      additionalTags:
                        additionalProperties:
                          type: string
                        description: AdditionalTags is an optional set of tags to
                          add to an instance, in addition to the ones added by default
                          by the Azure provider. If both the AzureCluster and the
                          AzureMachine specify the same tag name with different values,
                          the AzureMachine's value takes precedence.
                        type: object
                      allocatePublicIP:
                        description: AllocatePublicIP allows the ability to create
                          dynamic public ips for machines where this value is true.
                        type: boolean
                      availabilityZone:
                        properties:
                          enabled:
                            type: boolean
                          id:
                            type: string
                        type: object
                      identity:
                        default: None
                        description: Identity is the type of identity used for the
                          virtual machine. The type 'SystemAssigned' is an implicitly
                          created identity The generated identity will be assigned
                          a Subscription contributor role
                        enum:
                        - None
                        - SystemAssigned
                        type: string
                      image:
                        description: Image is used to provide details of an image
                          to use during VM creation. If image details are omitted
                          the image will default the Azure Marketplace "capi" offer,
                          which is based on Ubuntu.
                        properties:
                          id:
                            description: ID specifies an image to use by ID
                            type: string
                          marketplace:
                            description: Marketplace specifies an image to use from
                              the Azure Marketplace
                            properties:
                              offer:
                                description: Offer specifies the name of a group of
                                  related images created by the publisher. For example,
                                  UbuntuServer, WindowsServer
                                minLength: 1
                                type: string
                              publisher:
                                description: Publisher is the name of the organization
                                  that created the image
                                minLength: 1
                                type: string
                              sku:
                                description: SKU specifies an instance of an offer,
                                  such as a major release of a distribution. For example,
                                  18.04-LTS, 2019-Datacenter
                                minLength: 1
                                type: string
                              version:
                                description: Version specifies the version of an image
                                  sku. The allowed formats are Major.Minor.Build or
                                  'latest'. Major, Minor, and Build are decimal numbers.
                                  Specify 'latest' to use the latest version of an
                                  image available at deploy time. Even if you use
                                  'latest', the VM image will not automatically update
                                  after deploy time even if a new version becomes
                                  available.
                                minLength: 1
                                type: string
                            required:
                            - offer
                            - publisher
                            - sku
                            - version
                            type: object
                          sharedGallery:
                            description: SharedGallery specifies an image to use from
                              an Azure Shared Image Gallery
                            properties:
                              gallery:
                                description: Gallery specifies the name of the shared
                                  image gallery that contains the image
                                minLength: 1
                                type: string
                              name:
                                description: Name is the name of the image
                                minLength: 1
                                type: string
                              resourceGroup:
                                description: ResourceGroup specifies the resource
                                  group containing the shared image gallery
                                minLength: 1
                                type: string
                              subscriptionID:
                                description: SubscriptionID is the identifier of the
                                  subscription that contains the shared image gallery
                                minLength: 1
                                type: string
                              version:
                                description: Version specifies the version of the
                                  marketplace image. The allowed formats are Major.Minor.Build
                                  or 'latest'. Major, Minor, and Build are decimal
                                  numbers. Specify 'latest' to use the latest version
                                  of an image available at deploy time. Even if you
                                  use 'latest', the VM image will not automatically
                                  update after deploy time even if a new version becomes
                                  available.
                                minLength: 1
                                type: string
                            required:
                            - gallery
                            - name
                            - resourceGroup
                            - subscriptionID
                            - version
                            type: object
                        type: object
                      location:
                        type: string
                      osDisk:
                        properties:
                          diskSizeGB:
                            format: int32
                            type: integer
                          managedDisk:
                            properties:
                              storageAccountType:
                                type: string
                            required:
                            - storageAccountType
                            type: object
                          osType:
                            type: string
                        required:
                        - diskSizeGB
                        - managedDisk
                        - osType
                        type: object
                      providerID:
                        description: ProviderID is the unique identifier as specified
                          by the cloud provider.
                        type: string
                      sshPublicKey:
                        type: string
                      vmSize:
                        type: string
                    required:
                    - location
                    - osDisk
                    - sshPublicKey
                    - vmSize
                    type: object
                required:
                - spec
                type: object
            required:
            - template
            type: object
        type: object
    served: true
    storage: true
status:
  acceptedNames:
    kind: ""
    plural: ""
  conditions: []
  storedVersions: []
