apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- calico-vxlan.yaml
patches:
- path: patches/calico-node.yaml
  target:
    kind: DaemonSet
- path: patches/control-plane-tolerations.yaml
  target:
    kind: Deployment
    name: calico-kube-controllers
    namespace: kube-system
- path: patches/azure-mtu.yaml
- path: patches/replace-docker-with-quay.yaml
